name: Build and pack extension

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write  # Ensures the token can create releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all tags are fetched

      - name: Get latest tag
        id: get_tag
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
    
      - name: Install web-ext globally
        run: npm install -g web-ext
    
      - name: Build project
        run: npm run build
    
      - name: Pack Firefox extension
        run: web-ext build --source-dir dist/ --artifacts-dir ./build/ --filename persian-calendar.xpi --overwrite-dest
    
      - name: Zip extension files for Edge
        run: zip -r ./build/persian-calendar.zip ./dist
    
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}  # Use the dynamically fetched tag
          files: |
            build/persian-calendar.xpi
            build/persian-calendar.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
